@startuml "GATT-Client_overview"
skinparam classAttributeIconSize 0
title GATT-Client overview

class JenkinsApiHandler <<actor>>

HeadHandler *--> JenkinsApiHandler
HeadsManager o--> "1..*" HeadHandler
HeadHandler *--> GattServerConnector

main *--> HeadsManager
HeadsManager --> ConfigurationHandler
HeadsManager o--> "0..*" HeadConfiguration
ConfigurationHandler --> HeadConfiguration

@enduml