@startuml "GATT-Client_overview"
skinparam classAttributeIconSize 0
title GATT-Client overview

class jenkins <<actor>>

HeadHandler --> JenkinsJobManager
HeadHandler o--> HeadConfiguration
HeadHandler o--> GattServerConnector
JenkinsJobManager *--> jenkins
HeadsManager o--> "1..*" HeadHandler

main *--> HeadsManager
main *--> SignalHandler
HeadsManager --> ConfigurationHandler
ConfigurationHandler --> HeadConfiguration

@enduml