@startuml "GATT-Client_overview"
skinparam classAttributeIconSize 0
title GATT-Client overview

GattClient *--> JenkinsApiHandler
GattClientManager o--> "1..*" GattClient
GattClient *--> GattServerConnector

main *--> GattClientManager
GattClientManager --> ConfigurationHandler
GattClientManager o--> "0..*" HeadConfiguration
ConfigurationHandler --> HeadConfiguration

@enduml