@startuml "GATT-Server_overview"
skinparam classAttributeIconSize 0
title GATT-Server overview

interface BLECharacteristicCallbacks <<interface>>
interface ColorHandlerInterface <<interface>> 

BLECharacteristicCallbacks <|.. GattColorLedServer
ColorHandlerInterface <|.. NeoPixelHandler
ColorHandlerInterface <--o GattColorLedServer
GattColorLedServer <.. main
NeoPixelHandler <.. main

@enduml
