name: jenkins-head-controller-ci

on:
  push:
    paths: 
      - 'BLE-GATT-Client/**'
      - '!BLE-GATT-Client/doc/**'
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: 'BLE-GATT-Client/'

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: excitedleigh/setup-nox@1.0.0
    - run: nox -s lint
      
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: excitedleigh/setup-nox@1.0.0
    - run: nox -s tests
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: BLE-GATT-Client/coverage.xml
        flags: unittests
        env_vars: PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
    
